<?php

// File automatically generated by PHPEdit
// PHPEdit's unit tests extension might not work as expected if you modify this file

require_once 'PHPUnit/Util/Filter.php';

PHPUnit_Util_Filter::addFileToFilter(__FILE__);

if (!defined('PHPUnit_MAIN_METHOD')) {
    define('PHPUnit_MAIN_METHOD', 'system_classes_AllTests::main');
    chdir(dirname(dirname(__FILE__)));
}

require_once 'PHPUnit/Framework/TestSuite.php';
require_once 'PHPUnit/TextUI/TestRunner.php';

// PHPEdit Inclusions -- dot not remove this comment
require_once dirname(__FILE__) . DIRECTORY_SEPARATOR . 'filecacheTest.php';
require_once dirname(__FILE__) . DIRECTORY_SEPARATOR . 'remoterequestTest.php';
require_once dirname(__FILE__) . DIRECTORY_SEPARATOR . 'aclTest.php';
require_once dirname(__FILE__) . DIRECTORY_SEPARATOR . 'formatTest.php';
require_once dirname(__FILE__) . DIRECTORY_SEPARATOR . 'bitmaskTest.php';
require_once dirname(__FILE__) . DIRECTORY_SEPARATOR . 'colorUtilsTest.php';
require_once dirname(__FILE__) . DIRECTORY_SEPARATOR . 'utilsTest.php';
require_once dirname(__FILE__) . DIRECTORY_SEPARATOR . 'uuidTest.php';
require_once dirname(__FILE__) . DIRECTORY_SEPARATOR . 'tagTest.php';
require_once dirname(__FILE__) . DIRECTORY_SEPARATOR . 'versionTest.php';
// /PHPEdit Inclusions -- dot not remove this comment

class system_classes_AllTests
{
    public static function main()
    {
        PHPUnit_TextUI_TestRunner::run(self::suite());
    }

    public static function suite()
    {
        $suite = new PHPUnit_Framework_TestSuite('PHPUnit_Framework');

		// PHPEdit Tests suites -- dot not remove this comment
		$suite->addTestSuite('FileCacheTest');
		$suite->addTestSuite('RemoteRequestTest');
		$suite->addTestSuite('FormatTest');
		$suite->addTestSuite('BitmaskTest');
		$suite->addTestSuite('ColorUtilsTest');
		$suite->addTestSuite('UtilsTest');
		$suite->addTestSuite('UUIDTest');
		$suite->addTestSuite('TagTest');
		$suite->addTestSuite('VersionTest');
		// /PHPEdit Tests suites -- dot not remove this comment

        return $suite;
    }
}

if (PHPUnit_MAIN_METHOD == 'system_classes_AllTests::main') {
    system_classes_AllTests::main();
}
?>
